version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
        container_name: elasticsearch_elasticsearch_1

        ports:
         - "9200:9200"
         - "9300:9300"

        volumes:
            - ./data:/usr/share/elasticsearch/data
            - ./plugins:/usr/share/elasticsearch/plugins
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
              - bootstrap.memory_lock=true
              - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        mem_limit: 1g